version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'

# For JSON Files
       - package-ecosystem: "json"
    directory: "/"
    schedule:
      interval: "weekly" 
  
  